### PR TITLE
Ability to switch between webhooks

### PR DESCRIPTION
**Pull request by 0neBeerLeft**
now you can change the webhook after building the exe

### CODE REVIEW

**Comment by CactusHamster** [comment]
I'm not sure if I like the need for a pastebin url, but it seems like it could be a useful feature. Maybe it could be optional?

**Comment by 0neBeerLeft** [comment]
it dosent have to be a pastebin link, you can you any other paste service

**Comment by CactusHamster** [comment]
Yeah- I meant I don't like the idea that you have to use an external online service in the first place. This would be great as an **optional** feature. Maybe you could use a simple conditional statement? It's a great idea, but I know I would prefer the option of keeping the webhook url option as it was before.

**Comment by 0neBeerLeft** [comment]
> Yeah- I meant I don't like the idea that you have to use an external online service in the first place. This would be great as an **optional** feature. Maybe you could use a simple conditional statement? It's a great idea, but I know I would prefer the option of keeping the webhook url option as it was before.

yeah i agree with you

**Pull request closed without merging**
